@startuml
scale 2
title 线程流程图
(*) --> Thread
-->[new Thread()]初始状态
-->[t.start()]可运行
-right>[OS调度选中]运行中
-left>[时间片用完\nthread.yeild()]可运行
运行中-left>[等待用户输入\nthread.sleep()\n t2.join()] 阻塞状态
-->[用户输入结束\nsleep结束\njoin的线程结束]可运行
运行中-down>[o.wait()] 等待队列
-->[wait时间到\no.notify()\no.notifyall()]锁池状态
-->[拿到对象的锁标记]可运行
运行中-->[synchronized] 锁池状态
运行中-right>[run结束 main结束](*)
@enduml